dist: trusty
sudo: required
group: beta
language: node_js
node_js:
  - "8"
before_install:
  - npm i -g jshint
env:
  -
  - SOLIDITY_COVERAGE=true
matrix:
  fast_finish: true
  allow_failures:
    - env: SOLIDITY_COVERAGE=true
script:
  - set -e
  - jshint --show-non-errors test/*.js || echo "Errors in jshint ignored bc it doesn't support async/await"
  - npm test
before_deploy: npm run buildfornpm
deploy:
  provider: npm
  email: augusto.lemble@gmail.com
  skip_cleanup: true
  api_key: $NPM_TOKEN
  on:
    repo: windingtree/wt-contracts
    tags: true

